Package: c-ares
Maintainer: Marmalade Package Team <packages@ideaworkslabs.com>
Mkbs: c-ares.mkb
Libraries: cares
Homepage: http://c-ares.haxx.se/
Description:
  c-ares is a C library that performs DNS requests
  and name resolves asynchronously.
Contents:
 - ares_build.h            : h/ares_build.h
 - upstream/ares_dns.h     : h/ares_dns.h
 - upstream/ares_version.h : h/ares_version.h
 - upstream/ares.h         : h/ares.h
 - upstream/ares_rules.h   : h/ares_rules.h
Contents-Source:
 - c-ares.mkf
 - c-ares.mkb
 - ares_config.h
 - ares_build.h
 - example/ahost.c
 - example/ahost.mkb
 - example/data/app.icf
 - example/data/etc/resolv.conf
