Package: c-ares
Version: 1.7.3
Revision: 2
Maintainer: Marmalade Package Team <packages@ideaworkslabs.com>
Mkbs: c-ares.mkb
Description:
  c-ares is a C library that performs DNS requests
  and name resolves asynchronously.
Contents:
 - ares_build.h            : h/ares_build.h
 - upstream/ares_dns.h     : h/ares_dns.h
 - upstream/ares_version.h : h/ares_version.h
 - upstream/ares.h         : h/ares.h
 - upstream/ares_rules.h   : h/ares_rules.h
 - lib/arm/cares_d.a
 - lib/arm/libcares.a
 - lib/arm/libcares_d.a
Contents-src:
 - c-ares.mkf
 - c-ares.mkb
 - ares_config.h
 - ares_build.h
 - example/ahost.c
 - example/ahost.mkb
 - example/data/app.icf
 - example/data/etc/resolv.conf
Contents-platform:
  win32:
    - lib/x86/cares.lib
    - lib/x86/cares_d.lib
  linux:
    - lib/x86/linux/libcares.a
    - lib/x86/linux/libcares_d.a
  macosx:
    - lib/x86/darwin/libcares.a
    - lib/x86/darwin/libcares_d.a
